@startuml
package core{
    class Task
    class Interval
    class Project
    abstract class Activity
    class Application
    ' interface UserInterface
    class Clock

    package java.util{
        class Observable
        interface Observer
        }
    package java.time{
           class LocalDateTime
           class Duration
           class DateTimeFormatter
           class Timer
        }
    package org.json{
        class JSONObject
        class JSONArray
        class JSONTokener
        class FileWriter
    }
    enum timePeriods{
        MONTHLY: int=0
        DAILY: int=1
        YEARLY: int=2
    }
}


abstract Activity{
    - name: String
    - initalDateTime: LocalDateTime
    - finalDateTime: LocalDateTime
    - duration: Duration
    - active : boolean
    + {abstract}calculateDuration(): void
}
class Application{
    + TotalTimeSpent(activity: Activity,period: int ):LocalDateTime
    + readDataFromJSON():void
    + saveDataToJSON(): void
    + {static}main(String[]: args):void
}
class Project{
    + TotalTimeSpent(activity: Activity,period: int ):LocalDateTime
    + calculateDuration(): void
}
class Task{
    + NotifyApplication():void
    + startTask():void
    + stopTask():void
    + pauseTask():void
    + TotalTimeSpent(period: int ):LocalDateTime
    + calculateDuration(): void
}
class Interval{
    - start : LocalDateTime
    - end : LocalDateTime
}
class Clock{
    - timer:Timer
    - dateTime: LocalDateTime
    - tick(): void
    +startTimer():void
}
Application "activities " --* "*"Activity
Project --|> Activity
Project "activities "*-->"*"Activity
Task --|> Activity
Task "intervals"*-->"*"Interval
Clock --|> Observable
Interval ..|> Observer




@enduml